version: "3"

volumes:
  m2:

services:
  
  midenfy:  
    build: .
    working_dir: /home
    volumes:
      - $PWD:/home
      - m2:/root/.m2
    entrypoint: ["node", "/app/midenfy.js"]
  
  console:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: /bin/bash
    
  watch:  
    build: .
    working_dir: /home
    ports:
      - "9630:9630"
    volumes:
      - .:/home
      - m2:/root/.m2
    networks:
      - default
    entrypoint: npx shadow-cljs watch script --config-merge '{:http {:host "watch"}}'
