version: "3"

volumes:
  m2:

services:
  
  midenfy:  
    build: .
    working_dir: /home
    volumes:
      - $PWD:/home
      - m2:/root/.m2
    entrypoint: ["node", "/app/midenfy.js"]
  
  console:  
    build: .
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
    entrypoint: /bin/bash
